; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = default.csv
lib_deps =
  olikraus/U8g2 @ ^2.36.18
  makuna/NeoPixelBus @ ^2.8.1
  bblanchon/ArduinoJson @ ^7.2.1
  h2zero/NimBLE-Arduino @ ^2.3.0
monitor_speed = 115200
